### ISSUE TITLE
設定ファイルについて

### ISSUE THREAD

**Issue by Comamoca** [Comamoca/scaffox#3]
設定ファイルについては以下の仕様にしたいと考えています。

- TOML形式
- 保存先は `$XDG_CONFIG_HOME/scaffox/config.toml`

実装についてですが、Denoのstdにtomlライブラリがあるので読み込みにはそれを使い、設定ファイルの形式についてはzod等のバリデータでチェックを行なうようにする予定です。

設定ファイルに保存するデータについてはユーザー名やプロンプトのデフォルトの選択肢などを想定しています。

現状自分が考えている形式のサンプルです。

```toml
[user]
# ライセンスファイルの生成などに用いるユーザー情報
name = "Comamoca"

[repository]
# デフォルトのscaffoldリポジトリ
repo = "https://github.com/comamoca/scaffold"

[prompt]
# プロンプトのデフォルトの選択肢
license = "MIT"
target_dir = "."
```
